// Yushin-strings (i18n) — verbatim overgenomen uit extracted.js
// (const BOT_NAME, const STRINGS_BY_LANG) voor de nieuwe SaaS-client
// (taak #72). GEEN inhoudelijke wijzigingen. NB: bevat ook een gedeeltelijke
// fr-vertaling (nog niet volledig/nagekeken, taak #40) — de nieuwe client
// biedt vooralsnog enkel nl/en aan (AVAILABLE_LANGS), dus dat is onschadelijk.

const BOT_NAME = "Yushin";

const STRINGS_BY_LANG = {
  nl: {
    langName:"Nederlands",
    htmlTitle:"Yushin — TCM Bilan", h1Sub:"TCM Bilan",
    headerTagline:"Gestructureerde TCM-anamnese met werkhypothese",
    settingsBtnTitle:"Secties aan/uit zetten",
    a11yBtnTitleOn:"Grotere tekst / toegankelijkheidsmodus",
    a11yBtnTitleOff:"Terug naar normale tekstgrootte",
    stepperStart:"Start", stepperConclusion:"Conclusie",
    progressLabel:(n,total)=>`Vraag ${n} van ${total}`, progressDone:"Klaar",
    settingsTitle:"Secties aan/uit",
    settingsHint:"Vink secties uit die je voor deze praktijk niet wil gebruiken. Wijzigingen gelden bij de volgende (her)start.",
    settingsClose:"Sluiten", settingsApply:"Toepassen en herstarten",
    restartBtn:"↺ Opnieuw beginnen", prevBtn:"⬅ Vorige vraag",
    voiceOn:"🔊 Spraak: aan", voiceOff:"🔇 Spraak: uit", voiceUnsupported:"🔇 Spraak niet ondersteund",
    voiceHintText:"Ik kan elke vraag ook hardop voorlezen — dat staat standaard uit. Wil je dat ik dat doe?",
    voiceHintBtn:"🔊 Ja, lees voor", voiceHintOnConfirm:"Spraak staat nu aan — ik lees vanaf nu elke vraag hardop voor.",
    therapyPlanOffer:"Wil je dat ik op basis van deze resultaten een vrijblijvend therapieplan-voorstel doe — aanbevolen punten en leefstijladvies per herkend patroon? Dit vervangt nooit je eigen klinische beoordeling, tong- en polsdiagnose.",
    therapyPlanYes:"Ja, toon een voorstel", therapyPlanNo:"Nee, liever niet",
    therapyPlanTitle:"💡 Vrijblijvend therapieplan-voorstel",
    therapyPlanAskMei:"🗨️ Laat Yushin het toelichten",
    therapyPlanMenuIntro:"Ik kan je hier kort meer over vertellen. Waarover wil je dat ik uitleg geef?",
    therapyPlanBackToMenu:"← Terug naar overzicht",
    therapyPlanPoints:"Aanbevolen punten", therapyPlanLifestyle:"Leefstijl/voeding",
    therapyPlanUnmatched:(n)=>`Voor ${n} van de herkende patronen is er (nog) geen therapieplan-data beschikbaar — die zijn hier bewust weggelaten.`,
    therapyPlanDisclaimer:"<strong>Let op:</strong> dit is een algemeen, vrijblijvend voorstel op basis van de herkende TCM-patronen uit deze anamnese — geen vaste protocollen, en geen vervanging voor tong-/polsdiagnose of je eigen klinische beoordeling.",
    voiceSelectTitle:"Kies een stem voor Yushin — de kwaliteit hangt af van wat jouw browser/OS aanbiedt",
    skipSectionBtn:"Sectie overslaan", pdfBtn:"📄 Samenvatting als PDF",
    demoFillBtn:"🧪 Demo: automatisch invullen",
    demoFillConfirm:"Dit vult de volledige vragenlijst automatisch in met de eerste (willekeurige) optie per vraag, enkel om snel te testen. Gebruik dit nooit tijdens een echt consult — de resultaten zijn nep. Doorgaan?",
    voiceTip:'💡 Tip voor een merkbaar natuurlijkere stem: installeer een "Natural"-stem via je besturingssysteem (Windows: Instellingen → Tijd en taal → Spraak → Stemmen beheren → Nederlands toevoegen; macOS: Systeeminstellingen → Toegankelijkheid → Gesproken inhoud → Stemmen), kies die daarna hierboven in de lijst. Dit bestand werkt volledig offline, dus de stemkwaliteit is 100% wat je besturingssysteem zelf aanbiedt.',
    legendSummary:"Afkortingen / legende",
    micLabel:"🎤 Spreek je antwoord in", skipOptLabel:"— Overslaan —", skippedLabel:"(overgeslagen)",
    replayTitle:"Opnieuw voorlezen",
    onlyFemale:" (alleen getoond bij consult voor een vrouw)",
    onlyPediatric:" (alleen getoond bij pediatrie-optie)",
    onlyTherapist:" (alleen voor therapeut-rol)",
    voiceNoteWithMic:" Je kan elk antwoord ook gewoon inspreken via de microfoonknop.",
    voiceNoteNoMic:" (Inspreken via microfoon werkt het best in Chrome of Edge — in deze browser is die knop niet beschikbaar.)",
    greeting:(voiceNote)=>`Hallo, ik ben ${BOT_NAME}, je AI-assistent voor de klassieke TCM "10+2 vragen"-anamnese. Ik lees elke vraag ook hardop voor; kies het antwoord dat het best past, of sla er een over als ze niet van toepassing is.${voiceNote} Op het einde stel ik een overzicht samen van de meest waarschijnlijke TCM-patronen.`,
    askRole:"Wie vult deze anamnese in? Dit bepaalt welke vragen en welk detailniveau je te zien krijgt.",
    roleTherapist:"🩺 Ik ben de therapeut (volledige vragenlijst incl. polsdiagnose)",
    rolePatient:"🙂 Ik ben de patiënt (aangepaste vragenlijst)",
    askGender:"Voor welk geslacht wordt dit consult afgenomen? (bepaalt of de gynaecologie-sectie wordt getoond)",
    genderFemale:"Vrouw", genderMale:"Man", genderOther:"Anders / liever niet zeggen",
    askPediatric:"Betreft dit consult een kind, of wil je vragen over zwangerschap/geboorte(-voorgeschiedenis) meenemen?",
    pediatricYes:"Ja, neem de pediatrie-sectie mee", pediatricNo:"Nee, overslaan",
    groupStrong:"Sterk aanwezig", groupModerate:"Matig aanwezig", groupLight:"Licht aanwezig",
    disclaimerPolsBit:"en een gestructureerde polsdiagnose-vragenlijst ",
    disclaimerPolsSentence:" De polsdiagnose hier is een zelf-gerapporteerde vragenlijst, geen vervanging voor pols-palpatie door een opgeleide behandelaar.",
    disclaimerBase:(polsBit,polsSentence)=>`<strong>Belangrijk:</strong> dit is een educatief hulpmiddel gebaseerd op de klassieke TCM "10 vragen"-anamnese (uitgebreid met gynaecologie/pediatrie, orgaanklok ${polsBit}) en geeft een <em>werkhypothese</em>, geen medische diagnose. Tongdiagnose (visuele inspectie) is niet meegenomen en blijft essentieel voor een volledige TCM-diagnose.${polsSentence} Raadpleeg bij twijfel of ernstige klachten altijd een arts of bevoegde TCM-therapeut.`,
    ctxTherapist:"Ingevuld door therapeut", ctxPatient:"Ingevuld door patiënt", ctxNoRole:"Rol niet opgegeven",
    ctxFemale:"Vrouw", ctxMale:"Man", ctxNoGender:"Geslacht niet opgegeven", ctxPediatric:"pediatrie-sectie meegenomen",
    fileReadError:"Kon het geüploade bestand niet lezen — controleer of het een geldig, eerder geëxporteerd JSON-rapport is.",
    exportBtn:"💾 Exporteer resultaten (JSON)", compareBtn:"📂 Vergelijk met vorig rapport",
    simplifiedToggleLabel:"Vereenvoudigde patiëntversie voor de PDF",
    compareTitle:(dateLabel)=>`Vergelijking met vorig rapport (${dateLabel || "onbekende datum"})`,
    compareNew:"nieuw",
    allDone:"Alle vragen zijn doorlopen. Hier is mijn overzicht van de TCM-patronen die uit de antwoorden naar voren komen:",
    noPatterns:"Er kwamen geen specifieke patronen naar voren uit de gegeven antwoorden — mogelijk werden veel vragen overgeslagen, of wijst dit op een grotendeels gebalanceerd beeld. Overweeg de anamnese opnieuw te doorlopen met meer specifieke antwoorden, of vul aan met tongdiagnose en polsdiagnose.",
    reportTitle:"Samenvattend rapport", evidenceToggle:"Onderbouwing tonen",
    clockCardTitle:"Orgaanklok — jouw aandachtspunten",
    clockNoteHas:"De oranje segmenten zijn de tijdstippen waarop jij klachten aangaf — dat orgaan/meridiaan is volgens de orgaanklok op dat moment extra actief.",
    clockNoteNone:"Er kwamen geen uitgesproken tijdsgebonden klachten naar voren — de orgaanklok hieronder dient als referentie.",
    conclusion:(top,second)=>`Voorlopige conclusie (werkhypothese): het beeld wijst het meest in de richting van "${top}"` + (second ? `, mogelijk in combinatie met "${second}".` : "."),
    printBrandSub:"AI TCM-anamnese-assistent", printProtocolPill:"Protocol &ldquo;10+2 vragen&rdquo;",
    printTitleSimplified:"Jouw persoonlijke samenvatting", printTitleFull:"Samenvattend rapport — TCM anamnese",
    printNoPatterns:"Er kwamen geen specifieke patronen naar voren uit de gegeven antwoorden.",
    printWhatCameUp:"Wat kwam er naar voren?",
    printSimplifiedIntro:(p1,p2)=>`Op basis van je antwoorden ziet je behandelaar vooral aanwijzingen voor <strong>${p1}</strong>` + (p2?`, en in mindere mate voor <strong>${p2}</strong>`:"") + `. Dit is een eerste indruk, geen diagnose — je behandelaar bespreekt dit verder met je tijdens het consult.`,
    hypothesisTitle:"Werkhypothese",
    hypothesisText:(p1,p2)=>`Het beeld wijst het meest in de richting van <strong>${p1}</strong>` + (p2?`, mogelijk in combinatie met <strong>${p2}</strong>.`:"."),
    printIdentifiedPatterns:"Geïdentificeerde patronen",
    printClockSectionTitle:"Orgaanklok — signalen op tijdstip",
    printClockLegend:(who)=>`<span class="swatch" style="background:#c9762c"></span><strong>Gemarkeerde segmenten</strong> geven de tijdstippen weer waarop ${who} klachten of een wakker-moment rapporteerde. Volgens de klassieke orgaanklok (Zi Wu Liu Zhu) kan dit wijzen op een tijdgebonden disbalans in het bijbehorende orgaan/meridiaan.`,
    printClockWhoPatient:"jij", printClockWhoTherapist:"de patiënt",
    printFooter:(dateStr)=>`Gegenereerd door ${BOT_NAME} · ${dateStr} · Dit rapport vervangt geen professioneel medisch advies.`
  },
  en: {
    langName:"English",
    htmlTitle:"Yushin — TCM Assessment", h1Sub:"TCM Assessment",
    headerTagline:"Structured TCM intake with working hypothesis",
    settingsBtnTitle:"Turn sections on/off",
    a11yBtnTitleOn:"Larger text / accessibility mode",
    a11yBtnTitleOff:"Back to normal text size",
    stepperStart:"Start", stepperConclusion:"Conclusion",
    progressLabel:(n,total)=>`Question ${n} of ${total}`, progressDone:"Done",
    settingsTitle:"Sections on/off",
    settingsHint:"Uncheck sections you don't want to use in this practice. Changes take effect on the next (re)start.",
    settingsClose:"Close", settingsApply:"Apply and restart",
    restartBtn:"↺ Start over", prevBtn:"⬅ Previous question",
    voiceOn:"🔊 Voice: on", voiceOff:"🔇 Voice: off", voiceUnsupported:"🔇 Voice not supported",
    voiceHintText:"I can also read every question aloud — this is off by default. Would you like me to?",
    voiceHintBtn:"🔊 Yes, read aloud", voiceHintOnConfirm:"Voice is now on — I'll read every question aloud from now on.",
    voiceSelectTitle:"Choose a voice for Yushin — quality depends on what your browser/OS offers",
    skipSectionBtn:"Skip section", pdfBtn:"📄 Summary as PDF",
    demoFillBtn:"🧪 Demo: auto-fill",
    demoFillConfirm:"This automatically fills in the entire questionnaire with the first (arbitrary) option per question, for quick testing only. Never use this during a real consultation — the results are fake. Continue?",
    voiceTip:'💡 Tip for a noticeably more natural voice: install a "Natural" voice via your operating system (Windows: Settings → Time & Language → Speech → Manage voices → Add English; macOS: System Settings → Accessibility → Spoken Content → Voices), then pick it from the list above. This file works fully offline, so voice quality is entirely what your operating system offers.',
    legendSummary:"Abbreviations / legend",
    micLabel:"🎤 Speak your answer", skipOptLabel:"— Skip —", skippedLabel:"(skipped)",
    replayTitle:"Read aloud again",
    onlyFemale:" (only shown for a consult with a woman)",
    onlyPediatric:" (only shown when the pediatric option is selected)",
    onlyTherapist:" (only for the therapist role)",
    voiceNoteWithMic:" You can also simply speak your answer using the microphone button.",
    voiceNoteNoMic:" (Speaking your answer via microphone works best in Chrome or Edge — that button isn't available in this browser.)",
    greeting:(voiceNote)=>`Hello, I'm ${BOT_NAME}, your AI assistant for the classic TCM "10+2 questions" intake. I'll also read every question aloud; choose the answer that fits best, or skip one that doesn't apply.${voiceNote} At the end I'll put together an overview of the most likely TCM patterns.`,
    askRole:"Who is filling in this intake? This determines which questions and level of detail you'll see.",
    roleTherapist:"🩺 I'm the therapist (full questionnaire incl. pulse diagnosis)",
    rolePatient:"🙂 I'm the patient (adapted questionnaire)",
    askGender:"For which gender is this consult being taken? (determines whether the gynaecology section is shown)",
    genderFemale:"Woman", genderMale:"Man", genderOther:"Other / prefer not to say",
    askPediatric:"Is this consult for a child, or do you want to include questions about pregnancy/birth history?",
    pediatricYes:"Yes, include the pediatric section", pediatricNo:"No, skip",
    groupStrong:"Strongly present", groupModerate:"Moderately present", groupLight:"Slightly present",
    disclaimerPolsBit:"and a structured pulse-diagnosis questionnaire ",
    disclaimerPolsSentence:" The pulse diagnosis here is a self-reported questionnaire, not a substitute for pulse palpation by a trained practitioner.",
    disclaimerBase:(polsBit,polsSentence)=>`<strong>Important:</strong> this is an educational tool based on the classic TCM "10 questions" intake (extended with gynaecology/pediatrics, organ clock ${polsBit}) and provides a <em>working hypothesis</em>, not a medical diagnosis. Tongue diagnosis (visual inspection) is not included and remains essential for a complete TCM diagnosis.${polsSentence} If in doubt or with serious complaints, always consult a doctor or licensed TCM therapist.`,
    ctxTherapist:"Filled in by therapist", ctxPatient:"Filled in by patient", ctxNoRole:"Role not specified",
    ctxFemale:"Woman", ctxMale:"Man", ctxNoGender:"Gender not specified", ctxPediatric:"pediatric section included",
    fileReadError:"Couldn't read the uploaded file — check that it's a valid, previously exported JSON report.",
    exportBtn:"💾 Export results (JSON)", compareBtn:"📂 Compare with previous report",
    simplifiedToggleLabel:"Simplified patient version for the PDF",
    compareTitle:(dateLabel)=>`Comparison with previous report (${dateLabel || "unknown date"})`,
    compareNew:"new",
    allDone:"All questions have been answered. Here's my overview of the TCM patterns emerging from your answers:",
    noPatterns:"No specific patterns emerged from the given answers — possibly many questions were skipped, or this points to a largely balanced picture. Consider going through the intake again with more specific answers, or supplement with tongue and pulse diagnosis.",
    reportTitle:"Summary report", evidenceToggle:"Show reasoning",
    clockCardTitle:"Organ clock — your points of attention",
    clockNoteHas:"The orange segments are the times at which you reported complaints — according to the organ clock, that organ/meridian is extra active at that time.",
    clockNoteNone:"No pronounced time-related complaints emerged — the organ clock below serves as a reference.",
    conclusion:(top,second)=>`Preliminary conclusion (working hypothesis): the picture points most towards "${top}"` + (second ? `, possibly combined with "${second}".` : "."),
    printBrandSub:"AI TCM intake assistant", printProtocolPill:"&ldquo;10+2 questions&rdquo; protocol",
    printTitleSimplified:"Your personal summary", printTitleFull:"Summary report — TCM intake",
    printNoPatterns:"No specific patterns emerged from the given answers.",
    printWhatCameUp:"What came up?",
    printSimplifiedIntro:(p1,p2)=>`Based on your answers, your practitioner sees mainly indications of <strong>${p1}</strong>` + (p2?`, and to a lesser extent <strong>${p2}</strong>`:"") + `. This is a first impression, not a diagnosis — your practitioner will discuss this further with you during the consult.`,
    hypothesisTitle:"Working hypothesis",
    hypothesisText:(p1,p2)=>`The picture points most towards <strong>${p1}</strong>` + (p2?`, possibly combined with <strong>${p2}</strong>.`:"."),
    printIdentifiedPatterns:"Identified patterns",
    printClockSectionTitle:"Organ clock — time-based signals",
    printClockLegend:(who)=>`<span class="swatch" style="background:#c9762c"></span><strong>Highlighted segments</strong> show the times at which ${who} reported complaints or a waking moment. According to the classic organ clock (Zi Wu Liu Zhu), this may indicate a time-related imbalance in the corresponding organ/meridian.`,
    printClockWhoPatient:"you", printClockWhoTherapist:"the patient",
    printFooter:(dateStr)=>`Generated by ${BOT_NAME} · ${dateStr} · This report does not replace professional medical advice.`
  },
  fr: {
    langName:"Français",
    htmlTitle:"Yushin — Bilan TCM", h1Sub:"Bilan TCM",
    headerTagline:"Anamnèse MTC structurée avec hypothèse de travail",
    settingsBtnTitle:"Activer/désactiver des sections",
    a11yBtnTitleOn:"Texte agrandi / mode accessibilité",
    a11yBtnTitleOff:"Retour à la taille de texte normale",
    stepperStart:"Début", stepperConclusion:"Conclusion",
    progressLabel:(n,total)=>`Question ${n} sur ${total}`, progressDone:"Terminé",
    settingsTitle:"Activer/désactiver des sections",
    settingsHint:"Décochez les sections que vous ne souhaitez pas utiliser dans ce cabinet. Les changements prennent effet au (re)démarrage suivant.",
    settingsClose:"Fermer", settingsApply:"Appliquer et redémarrer",
    restartBtn:"↺ Recommencer", prevBtn:"⬅ Question précédente",
    voiceOn:"🔊 Voix : activée", voiceOff:"🔇 Voix : désactivée", voiceUnsupported:"🔇 Voix non prise en charge",
    voiceHintText:"Je peux aussi lire chaque question à voix haute — c'est désactivé par défaut. Souhaites-tu que je le fasse ?",
    voiceHintBtn:"🔊 Oui, lis à voix haute", voiceHintOnConfirm:"La voix est maintenant activée — je lirai désormais chaque question à voix haute.",
    voiceSelectTitle:"Choisissez une voix pour Yushin — la qualité dépend de ce que votre navigateur/système propose",
    skipSectionBtn:"Passer la section", pdfBtn:"📄 Résumé en PDF",
    demoFillBtn:"🧪 Démo : remplissage automatique",
    demoFillConfirm:"Ceci remplit automatiquement tout le questionnaire avec la première option (arbitraire) par question, uniquement pour tester rapidement. Ne jamais utiliser ceci lors d'une vraie consultation — les résultats sont fictifs. Continuer ?",
    voiceTip:'💡 Astuce pour une voix nettement plus naturelle : installez une voix "Natural" via votre système d\'exploitation (Windows : Paramètres → Heure et langue → Voix → Gérer les voix → Ajouter le français ; macOS : Réglages Système → Accessibilité → Contenu énoncé → Voix), puis sélectionnez-la ci-dessus. Ce fichier fonctionne entièrement hors ligne, la qualité de la voix dépend donc entièrement de ce que propose votre système.',
    legendSummary:"Abréviations / légende",
    micLabel:"🎤 Dictez votre réponse", skipOptLabel:"— Passer —", skippedLabel:"(passé)",
    replayTitle:"Relire à voix haute",
    onlyFemale:" (affiché uniquement pour une consultation avec une femme)",
    onlyPediatric:" (affiché uniquement si l'option pédiatrie est sélectionnée)",
    onlyTherapist:" (uniquement pour le rôle thérapeute)",
    voiceNoteWithMic:" Vous pouvez aussi simplement dicter votre réponse via le bouton microphone.",
    voiceNoteNoMic:" (La dictée via microphone fonctionne mieux sur Chrome ou Edge — ce bouton n'est pas disponible dans ce navigateur.)",
    greeting:(voiceNote)=>`Bonjour, je suis ${BOT_NAME}, votre assistante IA pour l'anamnèse classique MTC des « 10+2 questions ». Je lis aussi chaque question à voix haute ; choisissez la réponse qui convient le mieux, ou passez celles qui ne s'appliquent pas.${voiceNote} À la fin, je rassemble un aperçu des patterns MTC les plus probables.`,
    askRole:"Qui remplit cette anamnèse ? Cela détermine les questions et le niveau de détail affichés.",
    roleTherapist:"🩺 Je suis le/la thérapeute (questionnaire complet, diagnostic du pouls inclus)",
    rolePatient:"🙂 Je suis le/la patient(e) (questionnaire adapté)",
    askGender:"Pour quel genre cette consultation est-elle réalisée ? (détermine si la section gynécologie est affichée)",
    genderFemale:"Femme", genderMale:"Homme", genderOther:"Autre / préfère ne pas dire",
    askPediatric:"Cette consultation concerne-t-elle un enfant, ou souhaitez-vous inclure des questions sur la grossesse/l'accouchement (antécédents) ?",
    pediatricYes:"Oui, inclure la section pédiatrie", pediatricNo:"Non, passer",
    groupStrong:"Fortement présent", groupModerate:"Modérément présent", groupLight:"Légèrement présent",
    disclaimerPolsBit:"et un questionnaire structuré de diagnostic du pouls ",
    disclaimerPolsSentence:" Le diagnostic du pouls ici est un questionnaire auto-rapporté, et ne remplace pas la palpation du pouls par un praticien formé.",
    disclaimerBase:(polsBit,polsSentence)=>`<strong>Important :</strong> il s'agit d'un outil éducatif basé sur l'anamnèse classique MTC des « 10 questions » (étendue avec gynécologie/pédiatrie, horloge des organes ${polsBit}) et fournit une <em>hypothèse de travail</em>, pas un diagnostic médical. Le diagnostic par la langue (inspection visuelle) n'est pas inclus et reste essentiel pour un diagnostic MTC complet.${polsSentence} En cas de doute ou de plaintes sérieuses, consultez toujours un médecin ou un thérapeute MTC agréé.`,
    ctxTherapist:"Rempli par le/la thérapeute", ctxPatient:"Rempli par le/la patient(e)", ctxNoRole:"Rôle non précisé",
    ctxFemale:"Femme", ctxMale:"Homme", ctxNoGender:"Genre non précisé", ctxPediatric:"section pédiatrie incluse",
    fileReadError:"Impossible de lire le fichier importé — vérifiez qu'il s'agit d'un rapport JSON valide, exporté précédemment.",
    exportBtn:"💾 Exporter les résultats (JSON)", compareBtn:"📂 Comparer au rapport précédent",
    simplifiedToggleLabel:"Version patient simplifiée pour le PDF",
    compareTitle:(dateLabel)=>`Comparaison avec le rapport précédent (${dateLabel || "date inconnue"})`,
    compareNew:"nouveau",
    allDone:"Toutes les questions ont été parcourues. Voici mon aperçu des patterns MTC qui ressortent des réponses :",
    noPatterns:"Aucun pattern spécifique n'est ressorti des réponses données — peut-être beaucoup de questions ont-elles été passées, ou cela indique un tableau globalement équilibré. Envisagez de refaire l'anamnèse avec des réponses plus spécifiques, ou complétez avec le diagnostic de la langue et du pouls.",
    reportTitle:"Rapport de synthèse", evidenceToggle:"Afficher la justification",
    clockCardTitle:"Horloge des organes — vos points d'attention",
    clockNoteHas:"Les segments orange sont les horaires auxquels vous avez signalé des plaintes — selon l'horloge des organes, cet organe/méridien est particulièrement actif à ce moment-là.",
    clockNoteNone:"Aucune plainte liée à un horaire précis n'est ressortie — l'horloge des organes ci-dessous sert de référence.",
    conclusion:(top,second)=>`Conclusion provisoire (hypothèse de travail) : le tableau oriente le plus vers « ${top} »` + (second ? `, possiblement combiné à « ${second} ».` : "."),
    printBrandSub:"Assistante IA d'anamnèse MTC", printProtocolPill:"Protocole « 10+2 questions »",
    printTitleSimplified:"Votre résumé personnel", printTitleFull:"Rapport de synthèse — anamnèse MTC",
    printNoPatterns:"Aucun pattern spécifique n'est ressorti des réponses données.",
    printWhatCameUp:"Qu'est-ce qui est ressorti ?",
    printSimplifiedIntro:(p1,p2)=>`D'après vos réponses, votre thérapeute observe surtout des indices de <strong>${p1}</strong>` + (p2?`, et dans une moindre mesure de <strong>${p2}</strong>`:"") + `. Il s'agit d'une première impression, pas d'un diagnostic — votre thérapeute en discutera plus en détail avec vous lors de la consultation.`,
    hypothesisTitle:"Hypothèse de travail",
    hypothesisText:(p1,p2)=>`Le tableau oriente le plus vers <strong>${p1}</strong>` + (p2?`, possiblement combiné à <strong>${p2}</strong>.`:"."),
    printIdentifiedPatterns:"Patterns identifiés",
    printClockSectionTitle:"Horloge des organes — signaux horaires",
    printClockLegend:(who)=>`<span class="swatch" style="background:#c9762c"></span><strong>Les segments surlignés</strong> indiquent les horaires auxquels ${who} a signalé des plaintes ou un réveil. Selon l'horloge classique des organes (Zi Wu Liu Zhu), cela peut indiquer un déséquilibre horaire dans l'organe/méridien correspondant.`,
    printClockWhoPatient:"vous", printClockWhoTherapist:"le/la patient(e)",
    printFooter:(dateStr)=>`Généré par ${BOT_NAME} · ${dateStr} · Ce rapport ne remplace pas un avis médical professionnel.`
  }
};
